services:

  ##########################   BUILD COMMON LIBRARY   ##########################

  common:
    image: common
    build:
      context: ./common
    volumes:
      - common_data:/common

  ##########################   ATHENA (NEW POWERFUL LOG SYSTEM)   ##########################

  athena-elasticsearch:
    image: elasticsearch:7.16.1
    volumes:
      - ./athena/configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./athena/mounted/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "KJNESKDL{Qd1d"
      discovery.type: single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"

  athena-logstash:
    image: logstash:7.16.2
    volumes:
      - ./athena/configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./athena/configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./athena/configs/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    depends_on:
      - athena-elasticsearch

  athena-kibana:
    image: kibana:7.16.1
    volumes:
      - ./athena/configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk
    ports:
      - "5601:5601"
    depends_on:
      - athena-elasticsearch

  ##########################   HERMES (NEW POWERFUL ARBITRAGE SYSTEM)   ##########################

  hermes:
    image: hermes
    build:
      context: ./hermes
    volumes:
      - ./hermes/mounted/logs:/home/app/mounted/logs
      - common_data:/common
    ports:
      - "9090:9090"
    depends_on:
      - common

  hermes-filebeat:
    image: elastic/filebeat:7.16.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./hermes/configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./hermes/mounted/logs:/app/logs:ro
    networks:
      - elk
    depends_on:
      - athena-elasticsearch

volumes:
  common_data:

networks:
  elk:
    driver: bridge
